### ISSUE TITLE
18.12.-08.01.

### ISSUE THREAD

**Issue by bowl-of-rais** [d-isasterhub/IDP-simulated-user-exp#18]
### Miscellaneous
- [x] #23 (@d-isasterhub)
- [x] #19 (@bowl-of-rais)
- [x] #26 (@d-isasterhub)
- [x] #35 (@d-isasterhub)
- [x] make different output files for different parameters (@bowl-of-rais)
(see #35 !)
    - [x] profiling levels
    - [x] prompt variations

### Change profiling order 🔀
finding: profiling too early could cause hallucinations - let LLM describe first, then constrain behavior by profiling
approach: ask to describe the heatmap first (once for all fifty users), then give human features

- [x] #24 (@d-isasterhub)
- [x] #32 (@bowl-of-rais)

### Simulation Experiments 🏃

- [x] #27 (@d-isasterhub)
- [ ] baseline without any profiling (@d-isasterhub)
- [ ] easier questions (@d-isasterhub)

### Agreement questions 👍
profiling so far could include bird descriptions, accuracy

- [x] #25 (@d-isasterhub)
- [x] #36
- [x] #33 (@bowl-of-rais)
- [x] #41 (@d-isasterhub)

**Comment by d-isasterhub** [comment]
## Different profiling order notes

This is what the prompting currently looks like: 
![image](https://github.com/d-isasterhub/IDP-simulated-user-exp/assets/64603343/61eb0f8c-e174-4344-9e3a-dd329f7fb554)

The idea is the following:

First, get the heatmap description that will be reused for every (user, question) pair. This should only be done once, so save the answer in a file. When running the script, there should be a check if we already have a heatmap description:

> **SYSTEM**
> ...
>
> **USER**
> Attached is an image that consists of two sub-images. The top of the given image displays the original image of a bird and the bottom displays the same image combined with a heatmap that was generated by an explainable artificial intelligence model to explain the species predicted for the image. 
> Describe what areas of the bird are highlighted in red by the heatmap. _**Keep the number of tokens low.**_

```
response = openai.ChatCompletion.create(...)
```

Second, use the description to get a bird species classification prediction by chat completion:

> **SYSTEM**
> ...
>
> **USER**
> Attached is an image that consists of two sub-images. The top of the given image displays the original image of a bird and the bottom displays the same image combined with a heatmap that was generated by an explainable artificial intelligence model to explain the species predicted for the image. 
> Describe what areas of the bird are highlighted in red by the heatmap. 
>
> **ASSISTANT**
> [description]
>
> **USER**
> You believe that the classification model distinguishes between four possible species classes based on the following features: 
    - Rhinoceros Auklets: HEATMAP_FEATURES_RA
    - Least Auklets: HEATMAP_FEATURES_LA
    - Parakeet Auklets: HEATMAP_FEATURES_PA
    - Crested Auklets: HEATMAP_FEATURES_CA
> Based on the descriptions and the areas highlighted by the heatmap, which bird species do you think was predicted for the given image? Choose one of the following options for your answer:
    - Crested Auklet
    - Least Auklet
    - Parakeet Auklet
    - Rhinoceros Auklet
    For each bird description, explain why it might or might not be that species of bird based on your heatmap description.    Conclude your answer by stating only the selected option in the last line of your answer. **_Keep the number of tokens low._**

Mind that "_**Keep the number of tokens low.**_" appears in different modalities!

**Comment by d-isasterhub** [comment]
Maybe, we can somehow save more tokens since we already have the description. Do you have any ideas?

**Comment by d-isasterhub** [comment]
I just realized that the "Keep the number of tokens low" should also be included in the old prompting order if we want to rerun those simulations.
